// app/layout.tsx
import { CardProvider } from "@/app/context/cardContext";
import type { Metadata } from "next";
import "./styles/globals.scss";
import "./styles/roots.scss";
import "./styles/animations.scss";
import "./styles/typography.scss";
import SessionProviderClient from "@/app/SessionProviderClient";
import Navbar from "./navbar/navbar";

// _app.tsx ou _app.js

export const metadata: Metadata = {
  title: "Pokémon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <body>
        {/* Pour la session utilisateur */}
        <SessionProviderClient>
          <CardProvider>
            <Navbar />
            {children}{" "}
          </CardProvider>
        </SessionProviderClient>
      </body>
    </html>
  );
}
